"""Private Supabase Storage adapter (§79, §90, §135).

The platform stores uploaded media in **private** Supabase buckets. Buckets are
never made public and no public/signed URL is handed to the Flutter client: the
mobile app asks FastAPI for ``/media/{id}/content`` and the endpoint re-checks
ownership *before* calling :meth:`SupabaseStorage.read`. This adapter therefore
only ever runs on the server, behind the existing authorisation checks.

Bucket routing
--------------
:mod:`app.services.media_service` already generates paths whose **first segment
is the logical bucket name*::

    request-media/<customer>/<request>/<media>.jpg
    chat-media/<customer>/<conversation>/<attachment>.png
    payment-proofs/<customer>/<payment>/<proof>.webp
    complaint-media/<customer>/<complaint>/<attachment>.jpg

:func:`resolve_storage_path` splits that into ``(bucket, object_key)`` and
refuses anything not in :data:`BUCKET_BY_PREFIX`, so a compromised or buggy
caller cannot address an arbitrary bucket.

Path safety
-----------
Object keys are validated before any network call: absolute paths, ``..``
segments, empty segments, backslashes and control characters are rejected. The
validation is shared by every operation so ``write``/``read``/``exists``/
``delete`` can never disagree about what a path means.

Implementation
--------------
Speaks the Supabase Storage REST API directly through ``httpx`` (already a
project dependency). Pulling in the full ``supabase`` SDK would add PostgREST,
GoTrue and realtime clients that this architecture does not use — the database is
driven through SQLAlchemy and Auth is ours (§135).
"""

from __future__ import annotations

import re
from collections.abc import Iterator
from typing import Final
from urllib.parse import quote

import httpx

from app.core.config import settings
from app.core.exceptions import IntegrationUnavailableError, UploadRejectedError

#: Logical path prefix -> Supabase bucket. This mapping is the single source of
#: truth for bucket routing; anything outside it is rejected.
BUCKET_BY_PREFIX: Final[dict[str, str]] = {
    "request-media": "request-media",
    "chat-media": "chat-media",
    "payment-proofs": "payment-proofs",
    "complaint-media": "complaint-media",
}

_SEGMENT_RE: Final[re.Pattern[str]] = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")

#: Supabase Storage signals "no such object" with HTTP 400 and a body of
#: ``{"statusCode":"404","error":"not_found","code":"NoSuchKey"}``, so the
#: status alone is ambiguous. Both forms are treated as missing.
_NOT_FOUND_STATUSES: Final[frozenset[int]] = frozenset({404})


def _is_missing(response: httpx.Response) -> bool:
    """True when a Storage response means 'this object does not exist'.

    The REST API answers a missing object with HTTP 400 and a ``statusCode``/
    ``error`` pair describing a 404, which is indistinguishable from a real bad
    request by status code alone. Only these two signals are inspected, so a
    genuine 400 (bad bucket, refused mime type) still raises.
    """
    if response.status_code in _NOT_FOUND_STATUSES:
        return True
    if response.status_code != 400:
        return False
    try:
        body = response.json()
    except ValueError:
        return False
    if not isinstance(body, dict):
        return False
    return body.get("statusCode") == "404" or body.get("error") == "not_found"

#: The buckets are created with ``allowed_mime_types`` restricted to these image
#: types, so an ``application/octet-stream`` upload is rejected with
#: ``invalid_mime_type`` even though the bytes are a valid image. The key's
#: extension is authoritative: paths are generated by ``media_service``, which
#: already validates the real content before the path is built.
_MIME_BY_EXTENSION: Final[dict[str, str]] = {
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "png": "image/png",
    "webp": "image/webp",
}

_FALLBACK_MIME: Final[str] = "image/jpeg"


def _content_type_for(key: str) -> str:
    """Derive the upload ``Content-Type`` from the object key extension."""
    _, _, extension = key.rpartition(".")
    return _MIME_BY_EXTENSION.get(extension.lower(), _FALLBACK_MIME)


class StorageObjectNotFound(FileNotFoundError):
    """Raised when an object key does not exist.

    Subclasses :class:`FileNotFoundError` so it is indistinguishable from the
    behaviour of :class:`~app.services.media_service.LocalPrivateStorage` and the
    streaming endpoints keep a single code path.
    """


def resolve_storage_path(path: str) -> tuple[str, str]:
    """Split a logical storage path into ``(bucket, object_key)``.

    Raises :class:`UploadRejectedError` for traversal attempts, absolute paths,
    malformed segments and unknown buckets. Called by every operation so the
    four storage methods cannot disagree about path interpretation.
    """
    if not path or not path.strip():
        raise UploadRejectedError("Invalid storage path.")

    # Normalise nothing implicitly: backslashes and absolute paths are refused
    # outright rather than being silently rewritten.
    if "\\" in path or "\x00" in path:
        raise UploadRejectedError("Invalid storage path.")
    if path.startswith("/") or path.endswith("/"):
        raise UploadRejectedError("Invalid storage path.")

    segments = path.split("/")
    if any(segment in {"", ".", ".."} for segment in segments):
        raise UploadRejectedError("Invalid storage path.")
    if any(not _SEGMENT_RE.match(segment) for segment in segments):
        raise UploadRejectedError("Invalid storage path.")

    prefix, remainder = segments[0], segments[1:]
    bucket = BUCKET_BY_PREFIX.get(prefix)
    if bucket is None:
        raise UploadRejectedError("Invalid storage path.")
    return bucket, "/".join(remainder)


class SupabaseStorage:
    """Private-object storage over the Supabase Storage REST API.

    Implements the same contract as
    :class:`~app.services.media_service.LocalPrivateStorage`::

        write(path, content) -> str
        read(path) -> bytes
        exists(path) -> bool
        delete(path) -> None

    Authentication uses the **service role key**, which bypasses Storage RLS.
    That is safe here only because every call site sits behind the FastAPI
    authorisation layer; the key must never reach a client (§12).
    """

    provider = "supabase"

    def __init__(
        self,
        *,
        url: str | None = None,
        service_role_key: str | None = None,
        default_bucket: str | None = None,
        timeout_seconds: float | None = None,
        upload_timeout_seconds: float | None = None,
        client: httpx.Client | None = None,
    ) -> None:
        resolved_url = (url or settings.supabase_url or "").rstrip("/")
        resolved_key = service_role_key
        if resolved_key is None and settings.supabase_service_role_key is not None:
            resolved_key = settings.supabase_service_role_key.get_secret_value()

        if not resolved_url or not resolved_key:
            raise IntegrationUnavailableError(
                "Supabase storage is not configured."
            )

        self._base_url = resolved_url
        # Never logged, never included in an error message.
        self._key = resolved_key
        self._default_bucket = default_bucket or settings.supabase_storage_bucket
        self._timeout = timeout_seconds if timeout_seconds is not None else 30.0
        self._upload_timeout = (
            upload_timeout_seconds
            if upload_timeout_seconds is not None
            else float(settings.supabase_storage_upload_timeout_seconds)
        )
        # An injected client is used by the test-suite transport double.
        self._client = client
        self._owns_client = client is None

    # ------------------------------------------------------------- plumbing

    def _http(self) -> httpx.Client:
        if self._client is None:
            self._client = httpx.Client(
                base_url=self._base_url,
                timeout=self._timeout,
                follow_redirects=False,
            )
        return self._client

    def _auth_headers(self) -> dict[str, str]:
        """Auth headers are attached per request, not baked into the client.

        Keeping them on the request means an injected client still authenticates,
        and the credential never lives on a long-lived object.
        """
        return {
            "apikey": self._key,
            "Authorization": f"Bearer {self._key}",
        }

    def close(self) -> None:
        if self._client is not None and self._owns_client:
            self._client.close()
        self._client = None

    def __enter__(self) -> SupabaseStorage:
        return self

    def __exit__(self, *_exc: object) -> None:
        self.close()

    def _object_url(self, bucket: str, key: str) -> str:
        quoted = "/".join(quote(segment, safe="") for segment in key.split("/"))
        return f"/storage/v1/object/{quote(bucket, safe='')}/{quoted}"

    def _target(self, path: str) -> tuple[str, str]:
        bucket, key = resolve_storage_path(path)
        # Legacy/unprefixed paths are not part of the current contract; if one
        # ever shows up it lands in the configured default bucket rather than
        # failing, matching the historical local-storage behaviour.
        return bucket or self._default_bucket, key

    def _raise_for_status(self, response: httpx.Response, path: str, action: str) -> None:
        if response.is_success or _is_missing(response):
            return
        # Status only — never the body, which can echo the key or credentials.
        raise IntegrationUnavailableError(
            f"Storage {action} failed.",
            details={"status": response.status_code},
        )

    # ------------------------------------------------------------- contract

    def write(self, path: str, content: bytes) -> str:
        """Upload ``content`` to a private bucket. Returns the stored path."""
        bucket, key = self._target(path)
        if not isinstance(content, bytes):
            raise UploadRejectedError("Invalid upload payload.")
        if not content:
            raise UploadRejectedError("The uploaded file is empty.")

        response = self._http().post(
            self._object_url(bucket, key),
            content=content,
            headers={
                "Content-Type": _content_type_for(key),
                "x-upsert": "false",
                "Cache-Control": "no-store",
                **self._auth_headers(),
            },
            # Uploads must finish before the server responds, so they get the
            # longer write budget; a 12 MB body times out on the default one.
            timeout=httpx.Timeout(
                self._upload_timeout, connect=self._timeout, read=self._upload_timeout
            ),
        )
        self._raise_for_status(response, path, "upload")
        return path

    def read(self, path: str) -> bytes:
        bucket, key = self._target(path)
        response = self._http().get(
            self._object_url(bucket, key), headers=self._auth_headers()
        )
        if _is_missing(response):
            raise StorageObjectNotFound(f"No stored object at {path!r}.")
        self._raise_for_status(response, path, "download")
        return response.content

    def exists(self, path: str) -> bool:
        bucket, key = self._target(path)
        response = self._http().get(
            f"/storage/v1/object/info/{quote(bucket, safe='')}/{key}",
            headers=self._auth_headers(),
        )
        if _is_missing(response):
            return False
        self._raise_for_status(response, path, "stat")
        return response.is_success

    def delete(self, path: str) -> None:
        """Remove an object. Idempotent, matching the local adapter."""
        bucket, key = self._target(path)
        response = self._http().delete(
            self._object_url(bucket, key), headers=self._auth_headers()
        )
        if _is_missing(response):
            return
        self._raise_for_status(response, path, "delete")

    # -------------------------------------------------------------- buckets

    def buckets(self) -> Iterator[str]:
        """Configured bucket names, for verification and diagnostics."""
        yield from BUCKET_BY_PREFIX.values()


__all__ = [
    "BUCKET_BY_PREFIX",
    "StorageObjectNotFound",
    "SupabaseStorage",
    "resolve_storage_path",
]